

1
-
CREATE TABLE produits (
  idProduit int generated by default as identity primary key,
  designation varchar2
(50),
  info varchar2
(50),
  idCategorie int
);
ALTER TABLE produits ADD CONSTRAINT categories_produits_fk FOREIGN KEY  (idCategorie) REFERENCES Categories(IdCategorie);


CREATE TABLE categories (
  idCategorie int generated by default as identity primary key,
  nom varchar2
(50),
  commentaire varchar2
(50)
);


CREATE TABLE responsableVente (
  idRV int generated by default as identity primary key,
  nom varchar
(50),
  prenom
(50),
  email varchar
(50),
  idCategorie int
);
ALTER TABLE reponsableVente ADD CONSTRAINT categorie_rv_fk FOREIGN KEY  (idCategorie) REFERENCES Categories(IdCategorie);


SELECT p.nom, c.nom
FROM produits p
  JOIN categorie c   
USING
idCategorie;


SELECT rv.nom, p.designation
FROM reponsableVente rv
  JOIN produits p    
USING
IdCategorie;



3-
create bitmap index produits_categories_name_idx
on produits
(categories.name)
from produits, categories
on produit.IdCategorie = categories.idCategorie;

4-
SELECT *
from categories
WHERE nom='légumes';