OPTIMISATION
-------------------------------
drop table client;
create table client (id int generated by default as identity primary key,
Nom nvarchar2
(50));

drop table produit;
create table produit (id int generated by default as identity primary key,
designation nvarchar2
(200));

drop table commande;
create table commande (id int generated by default as identity primary key,
dateCommande date,
idClient int ,
constraint FK_Client Foreign key
(idClient) references client
(id));
references produit
(id));

create table ligneCommande (id int generated by default as identity primary key,
idCommande int,
idProduit int,
quantite number,
prix number,
constraint FK_commande foreign key
(idCommande)  references commande
(id),
constraint FK_Produit foreign key
(idProduit) references produit
(id));


select client.id Idclient, nom, commande.id idCommande,
  commande.dateCommande, produit.id idProduit, ligneCommande.quantite,
  ligneCommande.prix, designation
from client, commande, lignecommande, produit
where client.id = commande.idClient
  and commande.id = ligneCommande.idCommande
  and ligneCommande.idProduit = produit.id;

--- mise de la requete sous forme de Vue (table virtuel, construite sur la base d'une requete)
create view v_AllInfo
as
  select client.id Idclient, nom, commande.id idCommande,
    commande.dateCommande, produit.id idProduit, ligneCommande.quantite,
    ligneCommande.prix, designation
  from client, commande, lignecommande, produit
  where client.id = commande.idClient
    and commande.id = ligneCommande.idCommande
    and ligneCommande.idProduit = produit.id;

-- pour récupérer les infos de la base, il suffit :
select *
from v_AllInfo;

-- rechercher les commandes du client dont l'Id est 100
select *
from v_AllInfo
where Idclient = 100;
-- cette requet n'est pas Optimal parce que le systeme commence par créer la VUE (select *)
-- ensuite, il fait le filtre ..

--- employees, jobs, departments --  (Sous Oracle l'habitude est de créer le nom des tables au pluriels)
------------------
